# Generated by Django 3.1.7 on 2021-06-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=1222, null=True)),
                ('AccountNo', models.CharField(blank=True, max_length=122, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=122, null=True)),
                ('AccountNo', models.CharField(blank=True, max_length=7, null=True)),
                ('Email', models.CharField(blank=True, max_length=122, null=True)),
                ('AccountType', models.CharField(blank=True, max_length=122, null=True)),
                ('CurrentBalance', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer_Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderName', models.CharField(blank=True, max_length=122, null=True)),
                ('SenderAccountNo', models.CharField(blank=True, max_length=7, null=True)),
                ('ReceiverName', models.CharField(blank=True, max_length=122, null=True)),
                ('ReceiverAccountNo', models.CharField(blank=True, max_length=7, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
